language: java
jdk:
  - openjdk17

env:
  global:
    - LIQUIBASE_VERSION=4.32.0

before_install:
  - mkdir liquibase
  - tar -xzf resources/liquibase-pro-4.32.0.tar.gz -C liquibase
  - export PATH=$PWD/liquibase/liquibase-4.32.0:$PATH
  - echo "liquibase.licenseKey: $LIQUIBASE_LICENSE_KEY" > liquibase/liquibase-4.32.0/liquibase.properties
  - echo "liquibase.licenseKey: $LIQUIBASE_LICENSE_KEY" > liquibase/liquibase-$LIQUIBASE_VERSION/liquibase.properties

script:
  - liquibase --changeLogFile=changelog.xml \
              --url=jdbc:h2:mem:testdb \
              --username=sa \
              --password= \
              update
