language: minimal

services:
  - docker

env:
  global:
    - LIQUIBASE_VERSION=4.32.0
    - DB_NAME=liquibasedb
    - DB_USER=liquibase
    - DB_PASS=secret
    - DB_PORT=5432
    - DB_CONTAINER=pgdb
    - LIQUIBASE_LICENSE_KEY=secure_value_set_in_UI

before_script:
  - echo "[+] Starting PostgreSQL container..."
  - docker run -d --name $DB_CONTAINER \
      -e POSTGRES_DB=$DB_NAME \
      -e POSTGRES_USER=$DB_USER \
      -e POSTGRES_PASSWORD=$DB_PASS \
      -p $DB_PORT:5432 \
      postgres:14

  - echo "[+] Waiting for PostgreSQL to be ready..."
  - until docker exec $DB_CONTAINER pg_isready -U $DB_USER; do sleep 2; done

script:
  - echo "[+] Running Liquibase Pro update via Docker..."
  - docker run --rm \
      -e LIQUIBASE_LICENSE_KEY=$LIQUIBASE_LICENSE_KEY \
      -v $PWD:/liquibase/workspace \
      liquibase/liquibase:$LIQUIBASE_VERSION \
      --changeLogFile=changelog.xml \
      --url=jdbc:postgresql://172.17.0.1:$DB_PORT/$DB_NAME \
      --username=$DB_USER \
      --password=$DB_PASS \
      update
