language: java
jdk:
  - openjdk17

before_install:
  - curl -L -o https://package.liquibase.com/downloads/cli/liquibase/releases/pro/4.32.0/liquibase-pro-4.32.0.tar.gz
  - mkdir liquibase
  - tar -xzf liquibase.tar.gz -C liquibase
  - export PATH=$PWD/liquibase/liquibase-4.32.0:$PATH

script:
  - liquibase --version
  - liquibase --changeLogFile=changelog.xml \
              --url=jdbc:h2:mem:testdb \
              --username=sa \
              --password= \
              update
